export enum ROLE {
  ADMINISTRADOR = 'ROLE_ADMINISTRADOR',
  ENCARGADO = 'ROLE_ENCARGADO_EXPORTACION',
  REPRESENTANTE = 'ROLE_REPRESENTANTE_LEGAL',
  OPERADOR = 'ROLE_OPERADOR',
  TECNICO = 'ROLE_TECNICO_EXPORTACION',
  LABORATORIO = 'ROLE_LABORATORIO',
  JEFEDEPARTAMENTAL = 'ROLE_JEFEDEPARTAMENTAL',
  TECNICOINSPECCION = 'ROLE_TECNICO_INSPECCION',
  RELIQUIDACION = 'ROLE_TECNICO_RELIQUIDACION',
  RELIQUIDACIONTECNICO = 'ROLE_RELIQUIDACION',
  UAF = 'ROLE_RESPONSABLE_PAGOS',
}

export class ROLES_MODULES {
  static USER = [ROLE.ADMINISTRADOR, ROLE.REPRESENTANTE];
  static APM = [ROLE.REPRESENTANTE, ROLE.OPERADOR];
  static EXPORT_MANAGER = [ROLE.ENCARGADO];
  static HEAD_DEPARTMENT = [ROLE.JEFEDEPARTAMENTAL];
  static LABORATORY = [ROLE.LABORATORIO];
  static TECHNICAL = [ROLE.TECNICO];
  static INSPECTIONTECNICAL = [ROLE.TECNICOINSPECCION];
  static RELIQUIDACION = [ROLE.RELIQUIDACION];
  static UAF = [ROLE.UAF];
}
